// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO7csV4yYNunwLuRx3zyDbA1MMNoW1wsw',
    appId: '1:1029826978348:android:25151c258747ba21f72789',
    messagingSenderId: '1029826978348',
    projectId: 'cloudmessage-5109a',
    databaseURL: 'https://cloudmessage-5109a.firebaseio.com',
    storageBucket: 'cloudmessage-5109a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQIwsD-9n8TTnvppr_iqPQVrbpGqV9EL8',
    appId: '1:1029826978348:ios:687afa20088e4cedf72789',
    messagingSenderId: '1029826978348',
    projectId: 'cloudmessage-5109a',
    databaseURL: 'https://cloudmessage-5109a.firebaseio.com',
    storageBucket: 'cloudmessage-5109a.appspot.com',
    iosClientId: '1029826978348-qm5m3hpuddn9s4ottahndolk34q93qjd.apps.googleusercontent.com',
    iosBundleId: 'com.cahuroca.push-app',
  );
}
